#!/usr/bin/env python3
"""Generate `<name>.mdx.d.ts` declaration files in docs/src/types/_shared/
and migrate consumer pages to use the `@shared/...` import alias.

For every partial under docs/src/content/docs/_shared/:
  - Parse the @summary / @sections metadata block.
  - Write `docs/src/types/_shared/<name>.mdx.d.ts`. TypeScript resolves
    the `@shared/<name>.mdx` alias against this types dir first (with
    `allowArbitraryExtensions: true`) so VS Code shows a hover tooltip
    carrying the summary and section list at every <Component /> use site.

For every consumer page under docs/src/content/docs/ (excluding _shared/):
  - Rewrite `import X from '../_shared/foo.mdx';` to
    `import X from '@shared/foo.mdx';`. The alias is resolved by
    Vite/Astro at build time via tsconfig `paths` (the second target,
    pointing at the real `_shared/` directory).
  - Also rewrite legacy `'../_partials/foo.mdx'` and `'@partials/foo.mdx'`
    forms to the new alias for one-shot migration.

Also writes/refreshes `docs/src/types/_shared/README.md` so anyone who
opens that folder knows what it's for.

The script is idempotent. Running it twice produces no changes.

Usage:
    python scripts/sync_partial_metadata.py
    python scripts/sync_partial_metadata.py --check  # exit non-zero if it would change anything
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _partials_lib import (
    PARTIAL_ALIAS,
    PARTIALS_DIR,
    TYPES_DIR,
    list_consumer_pages,
    list_partials,
    parse_metadata,
    render_dts,
)

README_PATH = TYPES_DIR / "README.md"

README_CONTENT = """# `_shared/` type declarations (generated)

This directory holds **auto-generated** `<name>.mdx.d.ts` files — one per
partial under `docs/src/content/docs/_shared/`. Each declaration carries
the partial's `@summary` and `@sections` as JSDoc.

Together with the `@shared/*` path alias in `docs/tsconfig.json`,
TypeScript resolves an import like:

```ts
import Foo from '@shared/section-foo.mdx';
```

…by looking here **first** (where it finds `section-foo.mdx.d.ts` and uses
its JSDoc for hover tooltips), then falling through to the real `.mdx`
file in `docs/src/content/docs/_shared/` for runtime resolution by
Vite/Astro.

## Do not edit these files by hand

They are regenerated by:

```bash
python scripts/sync_partial_metadata.py
```

To change a tooltip, edit the `{/* @summary ... */}` block at the top of
the partial itself, then run the sync script.

Run `python scripts/sync_partial_metadata.py --check` locally before committing
to confirm no declaration is stale. This is a local guardrail — CI does not run
it (see `.github/workflows/pages.yml`).
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any file would change. Don't write anything.",
    )
    args = parser.parse_args()

    changes: list[tuple[Path, str]] = []

    if not TYPES_DIR.exists() and not args.check:
        TYPES_DIR.mkdir(parents=True, exist_ok=True)

    expected_dts: set[Path] = set()
    for partial in list_partials():
        meta = parse_metadata(partial)
        if meta is None:
            print(
                f"warning: {partial} has no metadata block; run lint_partials.py for details. "
                f"Skipping .mdx.d.ts generation.",
                file=sys.stderr,
            )
            continue
        dts_path = TYPES_DIR / f"{partial.name}.d.ts"
        expected_dts.add(dts_path)
        new_text = render_dts(meta)
        old_text = dts_path.read_text(encoding="utf-8") if dts_path.exists() else None
        if old_text != new_text:
            changes.append((dts_path, "create" if old_text is None else "update"))
            if not args.check:
                dts_path.parent.mkdir(parents=True, exist_ok=True)
                dts_path.write_text(new_text, encoding="utf-8")

    # Remove orphan .mdx.d.ts files (whose .mdx no longer exists).
    if TYPES_DIR.exists():
        for dts in TYPES_DIR.glob("*.mdx.d.ts"):
            if dts not in expected_dts:
                changes.append((dts, "delete"))
                if not args.check:
                    dts.unlink()

    # Remove legacy sibling shadows in the partials directory itself.
    for legacy in PARTIALS_DIR.glob("*.mdx.d.ts"):
        changes.append((legacy, "delete"))
        if not args.check:
            legacy.unlink()
    legacy_index = PARTIALS_DIR / "index.d.ts"
    if legacy_index.exists():
        changes.append((legacy_index, "delete"))
        if not args.check:
            legacy_index.unlink()

    # README in the types dir so the folder is self-explanatory.
    if not args.check or TYPES_DIR.exists():
        old_readme = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else None
        if old_readme != README_CONTENT:
            changes.append((README_PATH, "create" if old_readme is None else "update"))
            if not args.check:
                README_PATH.parent.mkdir(parents=True, exist_ok=True)
                README_PATH.write_text(README_CONTENT, encoding="utf-8")

    # Migrate consumer pages from relative to alias imports.
    for consumer in list_consumer_pages():
        text = consumer.read_text(encoding="utf-8")
        new_text = _rewrite_imports_to_alias(text)
        if new_text != text:
            changes.append((consumer, "update"))
            if not args.check:
                consumer.write_text(new_text, encoding="utf-8")

    if args.check:
        if changes:
            for path, what in changes:
                print(f"would {what}: {path}", file=sys.stderr)
            print(
                f"\n{len(changes)} file(s) need updating. "
                f"Run `python scripts/sync_partial_metadata.py`.",
                file=sys.stderr,
            )
            return 1
        print("OK: partial metadata is in sync.")
        return 0

    if changes:
        for path, what in changes:
            print(f"{what}: {path}")
        print(f"\n{len(changes)} file(s) updated.")
    else:
        print("Nothing to do.")
    return 0


_RELATIVE_PARTIAL_IMPORT = re.compile(
    r"""(import\s+\w+\s+from\s+['"])((?:\.\./)+_(?:shared|partials)/[^'"]+\.mdx)(['"])""",
)
_LEGACY_ALIAS_IMPORT = re.compile(
    r"""(import\s+\w+\s+from\s+['"])@partials/([^'"]+\.mdx)(['"])""",
)


def _rewrite_imports_to_alias(text: str) -> str:
    def repl_relative(m: re.Match[str]) -> str:
        rel = m.group(2)
        # Strip the `../`-prefix and `_shared/`/`_partials/` to get the bare filename.
        for needle in ("_shared/", "_partials/"):
            if needle in rel:
                idx = rel.index(needle) + len(needle)
                return f"{m.group(1)}{PARTIAL_ALIAS}{rel[idx:]}{m.group(3)}"
        return m.group(0)

    def repl_legacy_alias(m: re.Match[str]) -> str:
        return f"{m.group(1)}{PARTIAL_ALIAS}{m.group(2)}{m.group(3)}"

    text = _RELATIVE_PARTIAL_IMPORT.sub(repl_relative, text)
    text = _LEGACY_ALIAS_IMPORT.sub(repl_legacy_alias, text)
    return text


if __name__ == "__main__":
    sys.exit(main())
